shared: # used by more than one step in the pipeline
  target_unscaled_image_size: [256, 384] # imsz
  minimum_downscaled_image_size: [96, 96]
  fps: 100
  number_of_images_to_generate_per_input: 3001 # N_high
  seed: 0
  overwrite: False
  downscaling_factor: 6

image_loader:
  dataset_dir: "./data/raw/coco/test2014/"
  file_extension: "jpg"
  number_of_input_images: 50 # Nimgs: 500 # number of images to use for generation

image_preprocessor:
  max_image_size: null
  exponentiate: True
  exponentiattion_range: [0.7, 2.5]

video_generator:
  # A knot is a defined value for a transformation. We generate up to max_knots knots,
  # and then interpolate between to get a smooth transformation.
  max_number_of_scale_knots: 20 # max_knots_scale
  max_number_of_shift_knots: 20 # max_knots_shift
  max_number_of_rotation_knots: 20 # max_knots_rot

  max_scale_knot_value: 1 # max_val_scale
  max_shift_knot_multiplier_value: 1.5 # max_val_shift_mul
  max_rotation_knot_value: 2 # max_val_rot

  fill_mode: "wrap"

event_generator:
  sensor_config_path: "configs/data_generator/simulator/davis_model.yml"
  simulator_config_path: "configs/data_generator/simulator/evs_explorer.yml"

  thresholds: [1.35] #1.25, 1.4, 1.7, 2.2] # delta

  min_illuminance_lux_range: [450., 850.] # lum_min_range
  max_illuminance_lux_range: [10_000., 15_000.] # lum_max_range

event_discretizer:
  number_of_temporal_bins: 150 # N_low
  number_of_temporal_sub_bins_per_bin: 2

data_saver:
  output_dir: "./data/interim/coco/test/2subbins_new"
  save_events: True
  save_video: False
  h5_compression: 3
