network_loader:
  encoding:
    input_size: 2 # should equal to be subbins
    hidden_size: 24
    output_size: 64
    kernel_size: 3
  encoding_checkpoint_path: runs/continuous/third_run_with_mean_std_count/latest_checkpoint.pt
  decoding:
    input_size: 65 # should be output of encoding+1
    hidden_size: 128
    hidden_layers: 4
  decoding_checkpoint_path: runs/continuous/third_run_with_mean_std_count/latest_checkpoint.pt

network_handler:
  use_mean: true
  use_std: true
  use_count: true
  implicit: true
  feature_unfolding: true
  data_generator_target_image_size: [180, 240]

total_bins_in_video: 100